### ISSUE TITLE
websocket is already in closing or closed state

### ISSUE THREAD

**Issue by uuphoria2** [sm64jsarchived/sm64jsarchived#10]
![image](https://github.com/sm64jsarchived/sm64jsarchived/assets/155935644/799334cc-d910-43fd-9577-4a051748219f)
At the new domain for mmo (vanilla advanced thing at normal sm64jsarchive.com)
see it at: https://mmo.sm64jsarchive.com

**Comment by sm64jsarchived** [comment]
This is actively being worked on

**Comment by sm64jsarchived** [comment]
testing some stuff to get it working

**Comment by uuphoria2** [comment]
This issue is still happening

**Comment by uuphoria2** [comment]
error found: Tries to detect /ws/ or /wss tho these specific files dont exist yet

**Comment by uuphoria2** [comment]
Error found: default folder for websocket files isnt being  detected (The js file within it)

**Comment by uuphoria2** [comment]
@sm64jsarchived You can close this

**Comment by sm64jsarchived** [comment]
> @sm64jsarchived You can close this

ok
