### ISSUE TITLE
cant establish a connection wss and https thing

### ISSUE THREAD

**Issue by coop-enhanced** [sm64jsarchived/sm64jsarchived#13]
![image](https://github.com/sm64jsarchived/sm64jsarchived/assets/159720116/64045450-1046-423d-8726-84727dca3bb2)

**Comment by uuphoria2** [comment]
This problem is being looked into

**Comment by uuphoria2** [comment]
Issue found by "window.location.href" adding https (With host and ws its usually just wss://) at https://github.com/sm64jsarchived/sm64jsarchived/blob/MMO/src/mmo/socket.js#L57

**Comment by uuphoria2** [comment]
Fixed in commit https://github.com/sm64jsarchived/sm64jsarchived/commit/a99b4ad1c2202a3ba37b42833889cb4f64a60e47
