### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by uuphoria2** [sm64jsarchived/sm64jsarchived#15]
we need to get docker container running (The one simply named mmo.sm64jsarchive.com) which is the website so we can actually play this needs to get started sometime soon since it hasnt been running for a while

**Comment by sm64jsarchived** [comment]
I'll check the server logs

**Comment by sm64jsarchived** [comment]
Restarting the sm64jsarchive client for major errors

**Comment by sm64jsarchived** [comment]
I gotta update docker
