### ISSUE TITLE
Submit not working.

### ISSUE THREAD

**Issue by coop-enhanced** [sm64jsarchived/sm64jsarchived#20]
Nothing happens when i submit my name

**Comment by uuphoria2** [comment]
I'll make an update to "hopefully" fix it

**Comment by sm64jsarchived** [comment]
replying to this from my email directly cuz :trollface:

**Comment by uuphoria2** [comment]
We are actively rewriting the socket code

**Comment by uuphoria2** [comment]
This is being fixed quickly as of now.

**Comment by uuphoria2** [comment]
website no longer using websockets for main connections for advanced handler websockets coming soon

**Comment by uuphoria2** [comment]
this is now very irrelevant.

**Comment by uuphoria2** [comment]
docker servers almost ready

**Comment by sm64jsarchived** [comment]
Servers are functional now on https://mmo.sm64jsarchive.com

**Comment by sm64jsarchived** [comment]
This has been fixed fully
