### ISSUE TITLE
signin not working (TEST ISSUE WITH IMAGES IN THE NEW REWRITE)

### ISSUE THREAD

**Issue by coop-enhanced** [sm64jsarchived/sm64jsarchived#3]
![testissue](https://github.com/sm64jsarchived/sm64jsarchived/assets/159720116/7b73dd89-f38e-4880-bf12-b19c82ec38bf)

**Comment by uuphoria2** [comment]
this issue is currently being fixed real quick with new builds

**Comment by uuphoria2** [comment]
fixed
